export const INCREMENT_VALUE = 'INCREMENT_VALUE'
export const DECREMENT_VALUE = 'DECREMENT_VALUE'


export const GET_MEDICINE = 'GET_MEDICINE'
export const DELETE_MEDICINE = 'DELETE_MEDICINE'
export const UPDATE_MEDICINE = 'UPDATE_MEDICINE'
export const POST_MEDICINE = 'POST_MEDICINE'
export const LOAD_MEDICINE = 'LOAD_MEDICINE'
export const ERROR_MEDICINE = 'ERROR_MEDICINE'