export const INCREMENT_VALUE = 'INCREMENT_VALUE'
export const DECREMENT_VALUE = 'DECREMENT_VALUE'


export const GET_MEDICINE = 'GET_MEDICINE'
export const DELETE_MEDICINE = 'DELETE_MEDICINE'
export const UPDATE_MEDICINE = 'UPDATE_MEDICINE'
export const POST_MEDICINE = 'POST_MEDICINE'
export const LOAD_MEDICINE = 'LOAD_MEDICINE'
export const ERROR_MEDICINE = 'ERROR_MEDICINE'


export const GET_DOCTOR = 'GET_DOCTOR'
export const POST_DOCTOR = 'POST_DOCTOR'
export const DELETE_DOCTOR = 'DELETE_DOCTOR'
export const UPDATE_DOCTOR = 'UPDATE_DOCTOR'


export const POST_PATIENT = 'POST_PATIENT'
export const GET_PATIENT = 'GET_PATIENT'
export const DELETE_PATIENT='DELETE_PATIENT'
export const UPDATE_PATIENT='UPDATE_PATIENT'